### ISSUE TITLE
SyntaxError when viewing project issues

### ISSUE THREAD

**Issue by jdenisgiguere** [codacy/codacy-cli#5]
Hi!

I'm trying to use the codacy client.

When I launch codacy with the `-p` parameter,  I get the following output:

```
codacy -c ~/.codacy -p georchestra
```
```
undefined:6
<!DOCTYPE html>
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at module.exports.CodacyAPI.getProject (/usr/local/lib/node_modules/codacy-cli/src/api.js:87:23)
    at prepareResponse (/usr/local/lib/node_modules/codacy-cli/src/codacy-cli.js:34:18)
    at main (/usr/local/lib/node_modules/codacy-cli/src/codacy-cli.js:46:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/codacy-cli/src/codacy-cli.js:58:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

### Codacy version

`codacy -V`

`0.1.1`

### Node version

`node --version`

`v0.10.25`

**Comment by rtfpessoa** [comment]
Hi @jdenisgiguere,

This cli is currently not under development, and might be replaced in the future.

I issued a new release 0.2.0 to fix your issues.

**Comment by rtfpessoa** [comment]
@jdenisgiguere I am not sure if it runs on node versions higher than 0.10.
